# Generated by Django 4.1.7 on 2023-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_username_user_user_name_remove_user_firstname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="first name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="last name"
            ),
            preserve_default=False,
        ),
    ]
