# Generated by Django 4.1.7 on 2023-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_expenditure_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenditure",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("transportation", "Transportation"),
                    ("dress", "Dress"),
                    ("fuel", "Fuel"),
                ],
                default=None,
                max_length=100,
            ),
        ),
    ]
