# Generated by Django 4.1.7 on 2023-03-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_expenditure_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
